config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :references
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  validates :func, :usage_code, :usage_description, :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  layout 'reference_editer'
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  def index
    @references_i = Reference.where(category: 'Initialize')
    @references_g = Reference.where(category: 'GPIO Control')
    @references_o = Reference.where(category: 'Other')
    render layout: 'references'
  end

  def show
    render layout: 'references'
  end

  def new
    @reference = Reference.new
  end

  def create
    @reference = Reference.new(reference_params)
    if @reference.save
      redirect_to @reference, notice: 'Create succeed!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @reference.update(reference_params)
      redirect_to @reference, notice: 'Edit succeed!'
    else
      render 'edit'
    end
  end

  def destroy
    @reference.destroy
    redirect_to references_path, notice: 'Delete succeed!'
  end

  private

  def reference_params
    params.require(:reference).permit(:func, :usage_code, :usage_description, :category)
  end

  def set_reference
    @reference = Reference.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container"><p class="text-center">MINI-REFERENCE</p></div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WiringPi Mini-Reference</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/reference_editer.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WiringPi Mini-Reference</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<div class="container">
  <h1 class="text-center">WiringPi Mini-Reference</h1>
  <ul class="nav nav-pills nav-justified">
    <li role="presentation"><%= link_to 'Top', root_path %></li>
    <li role="presentation"><%= link_to 'Reference', references_path %></li>
    <li role="presentation" class="active"><%= link_to 'Reference Editer' %></li>
  </ul>
</div>
</header>

<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/references.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WiringPi Mini-Reference</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<div class="container">
  <h1 class="text-center">WiringPi Mini-Reference</h1>
  <ul class="nav nav-pills nav-justified">
    <li role="presentation"><%= link_to 'Top', root_path %></li>
    <li role="presentation" class="active"><%= link_to 'Reference', references_path %></li>
    <li role="presentation"><%= link_to 'Reference Editer', new_reference_path %></li>
  </ul>
</div>
</header>

<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WiringPi Mini-Reference</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<div class="container">
  <h1 class="text-center">WiringPi Mini-Reference</h1>
  <ul class="nav nav-pills nav-justified">
    <li role="presentation" class="active"><%= link_to 'Top', root_path %></li>
    <li role="presentation"><%= link_to 'Reference', references_path %></li>
    <li role="presentation"><%= link_to 'Reference Editer', new_reference_path %></li>
  </ul>
</div>
</header>

<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/references/_error.html.erb
<div class="alert alert-danger" role="alert">
  <ul>
  <% @reference.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

app/views/references/_form.html.erb
<%= form_for @reference, class: 'form-horizontal' do |f| %>

  <%= f.label :func, class: 'control-label', value: 'Function name (関数名)' %>
  <%= f.text_field :func, class: 'form-control' %><br>

  <%= f.label :usage_code, class: 'control-label', value: 'Usage code (一般的なコードの書き方)' %>
  <%= f.text_area :usage_code, class: 'form-control' %><br>

  <%= f.label :usage_description, class: 'control-label', value: 'Usage description (使い方の説明)' %>
  <%= f.text_area :usage_description, class: 'form-control' %><br>

  <%= f.label :category, class: 'control-label', value: 'Category (カテゴリー)' %>
  <%= f.select :category, ['Initialize', 'GPIO Control', 'Other'], {}, class: 'form-control' %><br>

  <%= f.submit 'Done!', class: 'btn btn-primary' %>
<% end %>

app/views/references/_list_references.html.erb
<table class="table">
  <% references.each do |ref| %>
    <tr>
      <th><%= link_to ref.func, ref %></th>
      <td><%= ref.category %></td>
    </tr>
  <% end %>
</table>

app/views/references/_page_notice.html.erb
<div class="alert alert-success">
  <p><%= notice %></p>
</div>

app/views/references/edit.html.erb
<div class="edit_reference">
  <div class="jumbotron">
    <h2 class="text-left">Edit Reference</h2>
    <p class="lead text-left">リファレンスを編集します。</p>
  </div>
  <%= render 'references/error' if @reference.errors.any? %>
  <%= render 'references/form' %>
</div>

app/views/references/index.html.erb
<div class="index_references">
  <%= render 'page_notice' if notice %>

  <div class="jumbotron">
    <h2 class="text-left">References</h2>
    <p class="lead">リファレンスの一覧ページです。</p>
  </div>

  <h3 class="text-left">Initialize (初期化, 基本)</h3>
  <div class="ref_init"><%= render 'references/list_references', references: @references_i %></div>

  <h3 class="text-left">GPIO Control (GPIO操作)</h3>
  <div class="ref_gpio"><%= render 'references/list_references', references: @references_g %></div>

  <h3 class="text-left">Other (その他)</h3>
  <div class="ref_other"><%= render 'references/list_references', references: @references_o %></div>
</div>

app/views/references/new.html.erb
<div class="new_reference">
  <div class="jumbotron">
    <h2 class="text-left">New Reference</h2>
    <p class="lead text-left">新しくリファレンスを作成します。</p>
    <p class="lead text-left">書き方は既存のものを参考にしてください。</p>
  </div>
  <%= render 'references/error' if @reference.errors.any? %>
  <%= render 'references/form' %>
</div>

app/views/references/show.html.erb
<div class="show_reference">
  <%= render 'page_notice' if notice %>

  <div class="jumbotron">
    <h2 class="text-left"><%= @reference.func %></h2>
    <%= simple_format(@reference.usage_description) %>
  </div>
  <div class="usage">
    <h2 class="text=left">Usage (使い方)</h2>
    <%= simple_format(@reference.usage_code, {}, wrapper_tag: 'pre') %>

  </div>
  <div class="to_otherpage">
    <%= link_to 'Edit...', edit_reference_path(@reference), class: 'btn btn-warning' %>
    <%= link_to 'Delete!', @reference, method: :delete, data: { comfirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
</div>

app/views/top/index.html.erb
<div class="top_index">
  <div class="jumbotron">
    <h2>Top Page</h2>
    <p class="lead">wiringPiの簡易リファレンスです。</p>
  </div>

  <div class="introduction">
    <h2>Introduction</h2>
    <pre>#include &lt;wiringPi.h&gt;</pre>
    <p class="lead">とすることでwiringPiライブラリを利用できます。</p>
    <br>
    <pre>$ cc -o hoge(実行時に使う名前) hoge.c(ソースコードファイル名) -lwiringPi</pre>
    <p class="lead">でコンパイルを行い，</p>
    <pre>$ sudo ./hoge(コンパイル時に指定した実行名)</pre>
    <p class="lead">で実行します。</p>
  </div>
</div>